CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT UNIQUE NOT NULL,
 volume INTEGER DEFAULT 0,
 expire_days INTEGER DEFAULT 30,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS configs (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INTEGER,
 uuid TEXT NOT NULL,
 config TEXT NOT NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
